### ISSUE TITLE
About rendering for the dataset

### ISSUE THREAD

**Issue by RuixiangXue** [TencentARC/FreeSplatter#3]
Thanks for sharing your awesome work!
I notice that the dataset is from the rendering image of some 3d asset, e.g., Objaverse
I want to know what kind of rendering engine? Can you share the script for making the dataset?

**Comment by bluestyle97** [comment]
We used blender for dataset rendering. Please refer to https://github.com/allenai/objaverse-xl/tree/main/scripts/rendering.

**Comment by RuixiangXue** [comment]
Thanks for your kind answer. I would also like to know how to render the depth map at the same time, because the link you provided does not seem to have this part implemented.
